MvcWorkspace/Models/Expense.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcWorkspace.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Expense Name")]
        public string ExpenseName { get; set; }
        
        [Required]
        [Range(1, int.MaxValue, ErrorMessage ="Yanlış Değer köşende ağlayabilirsin EZİK")]
        public int Amount { get; set; }
        
        
        [ForeignKey("ExpenseCategory")]
        [Display(Name = "Expense Category")]
        public int C_Id {get; set;}
        [ValidateNever]
        public ExpenseCategory ExpenseCategory {get; set;}
    }
}

MvcWorkspace/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Mvc;
using MvcWorkspace.Models;
using MvcWorkspace.Models.ViewModels;
using MvcWorkspace.Services;

namespace MvcWorkspace.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _service;
        public ExpenseController(IExpenseService service) 
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View(_service.GetExpenses());
        }

        public IActionResult Delete(int id) 
        {
            bool not = _service.Delete(id);
            if (not) return NotFound();
            return RedirectToAction("Index");
        }

        public IActionResult AddOrUpdate(int id)
        {
            ExpenseVM expenseVM = new ExpenseVM()
            {
                Expense = new Expense(),
                CategoryDropdown = _service.CategorySelectListItems()

            };
            
            if (id == 0)
                return View(expenseVM);
            else 
            {
                expenseVM.Expense = _service.GetExpense(id);
                return View(expenseVM);
            }
                
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddOrUpdate(Expense expense)
        {
                if (expense.Id == 0)
                {
                _service.Add(expense);
                }
                else
                {
                    _service.Update(expense);
                }

                return RedirectToAction("Index");
        }

        public IActionResult CategoryExpenses(int cid) 
        {
            IEnumerable<Expense> Expenses = _service.GetExpensesForCatName(cid);
            GetTotal(Expenses);
            ViewBag.ExpenseCat = _service.GetExpensesCatName(cid);
            return View(Expenses);
        }

        private void GetTotal(IEnumerable<Expense> expenses)
        {
            ViewBag.Amounts = 0;
            
            foreach (var exp in expenses) ViewBag.Amounts += exp.Amount;
        }
    }
}

MvcWorkspace/Views/Expense/AddOrUpdate.cshtml
@model MvcWorkspace.Models.ViewModels.ExpenseVM

<form method="post" asp-action="AddOrUpdate">
    <div class="p-3 col-12">
         <input type="hidden" asp-for="Expense.Id" />
        <h2 class="text-black-50 pl-3">Add Expense</h2>
        <div class="row col-6">
            <div class="pb-3">
                <label asp-for="Expense.ExpenseName" class="form-label"></label>
                <input asp-for="Expense.ExpenseName" class="form-control"/>
                <span asp-validation-for="Expense.ExpenseName" class="text-danger"></span>
            </div>
            <div class="pb-3">
                <label asp-for="Expense.Amount" class="form-label"></label>
                <input asp-for="Expense.Amount" class="form-control" />
                <span asp-validation-for="Expense.Amount" class="text-danger"></span>
            </div>
            <div class="pb-3">
                <label asp-for="Expense.C_Id" class="form-label"></label>
                <select asp-for="Expense.C_Id" class="form-control" asp-items="@Model.CategoryDropdown">
                    <option disabled selected>--- Select a Category ---</option>
                </select>
                <span asp-validation-for="Expense.C_Id" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-3 text-start">
                <a asp-action="Index" class="btn btn-outline-primary w-100 ">Back</a>
            </div>
            <div class="col-3 text-end">

                @{
                    if(Model.Expense.Id == 0)
                    {
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    }
                }
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

MvcWorkspace/Views/Expense/CategoryExpenses.cshtml
@model IEnumerable<Expense>
@{
    ViewData["Title"] = "Expense Categories";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-3">
                <h2 class="text-dark"> @ViewBag.ExpenseCat</h2>
                
            </div>
            <div class="col-3 text-end">
                <h3 class="text-danger">Amount Count: @ViewBag.Amounts</h3>
            </div>
    </div>
    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr class="align-middle text-primary">
                    <th>
                        Expense
                    </th>
                    <th>
                        Amount
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var expense in Model)
                {
                <tr class="align-middle">
                    <td width="20%">@expense.ExpenseName</td>
                    <td width="20%">@expense.Amount</td>
                </tr>
                }
            </tbody>
        </table> 
    }
    else
    {
        <p>No items created yet</p>
    }

</div>

MvcWorkspace/Views/Expense/Index.cshtml
@model IEnumerable<Expense>
@{
    ViewData["Title"] = "Expense Home";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Category: Expenses List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Expense" asp-action="AddOrUpdate" class="btn btn-primary">Create new Expense</a>
        </div>
    </div>
    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr class="align-middle text-primary">
                    <th>
                        Expense
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var expense in Model)
                {
                <tr class="align-middle">
                    <td width="20%">@expense.ExpenseName</td>
                    <td width="20%">@expense.Amount</td>
                     <td width="20%">
                         <a class="btn btn-outline-primary mx-2" asp-controller="Expense" asp-action="CategoryExpenses" asp-route-cid = "@expense.C_Id"> @expense.ExpenseCategory.ExpenseCName 
                         </a></td> 
                        
                    
                    <td width="30%" class="">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Expense" asp-action="AddOrUpdate" asp-route-id="@expense.Id" class="btn btn-outline-primary mx-2">Update</a>
                            <a asp-controller="Expense" asp-action="Delete" asp-route-id="@expense.Id" class="btn btn-outline-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table> 
    }
    else
    {
        <p>No items created yet</p>
    }

</div>