MvcWorkspace/Models/ExpenseCategory.cs
using System.ComponentModel.DataAnnotations;

namespace MvcWorkspace.Models
{
    public class ExpenseCategory
    {
        [Key]
        public int C_Id { get; set; }

        [Required]
        [Display(Name = "Expense Category Name")]
        public string ExpenseCName { get; set; }
    }
}

MvcWorkspace/Controllers/ExpenseCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MvcWorkspace.Data;
using MvcWorkspace.Models;

namespace MvcWorkspace.Controllers
{
    public class ExpenseCategoryController : Controller
    {
        private readonly AppDbContext _db;
        public ExpenseCategoryController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<ExpenseCategory> expenseCategories = _db.ExpenseCategories;
            return View(expenseCategories);
        }

        public IActionResult Delete(int id)
        {
            var expensec = _db.ExpenseCategories.Find(id);
            if (expensec == null || id == 0) return NotFound();
            _db.ExpenseCategories.Remove(expensec);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult AddOrUpdate(int id)
        {
            if (id == 0)
                return View(new ExpenseCategory());
            else
                return View(_db.ExpenseCategories.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddOrUpdate(ExpenseCategory expensec)
        {
            if (expensec.C_Id == 0)
            {
                _db.Add(expensec);
            }
            else
            {
                _db.Update(expensec);
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcWorkspace/Views/ExpenseCategory/AddOrUpdate.cshtml
@model MvcWorkspace.Models.ExpenseCategory

<form method="post" asp-action="AddOrUpdate">
    <div class="p-3 col-12">
         <input type="hidden" asp-for="C_Id" />
        <h2 class="text-black-50 pl-3">Add Expense Category</h2>
        <div class="row col-6">
            <div class="pb-3">
                <label asp-for="ExpenseCName" class="form-label"></label>
                <input asp-for="ExpenseCName" class="form-control"/>
                <span asp-validation-for="ExpenseCName" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-3 text-start">
                <a asp-action="Index" class="btn btn-outline-primary w-100 ">Back</a>
            </div>
            <div class="col-3 text-end">

                @{
                    if(Model.C_Id == 0)
                    {
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    }
                    else
                    {
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    }
                }
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

MvcWorkspace/Views/ExpenseCategory/Index.cshtml
@model IEnumerable<ExpenseCategory>
@{
    ViewData["Title"] = "ExpenseCategory Home";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expense Categories List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ExpenseCategory" asp-action="AddOrUpdate" class="btn btn-primary">Create new Expense Category</a>
        </div>
    </div>
    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr class="align-middle text-primary">
                    <th>
                        Expense Categories
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var expensecategory in Model)
                {
                <tr class="align-middle">
                    <td width="25%">@expensecategory.ExpenseCName</td>
                    <td width="30%" class="">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="ExpenseCategory" asp-action="AddOrUpdate" asp-route-id="@expensecategory.C_Id" class="btn btn-outline-primary mx-2">Update</a>
                            <a asp-controller="ExpenseCategory" asp-action="Delete" asp-route-id="@expensecategory.C_Id" class="btn btn-outline-danger mx-2">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table> 
    }
    else
    {
        <p>No items created yet</p>
    }

</div>